# Generated by Django 5.2.6 on 2025-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='estimated_profit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_price',
            field=models.FloatField(null=True),
        ),
    ]
