# Generated by Django 5.2.6 on 2025-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_trade_buy_price_alter_trade_estimated_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='actual_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed_profit', 'Closed with Profit'), ('closed_loss', 'Closed with Loss'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_loss_percent',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='trade',
            name='target_profit_percent',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='estimated_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
