# Generated by Django 5.2.6 on 2025-12-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trade_actual_profit_trade_closed_at_trade_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buy_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='close_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='commission_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
